// ignore_for_file: file_names

import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Connect face-to-face': 'Connect face-to-face\n',
          'with a registered': 'with a registered\n',
          'notary': 'notary.',
          'oboardingDescription1':
              "Revolutionizing Notarization establish trust through personal connections seamlessly connect face-to-face with verified notaries on notaryping.",
          'Skip': 'Skip',
          'Notaryping instant,': 'Notaryping instant, ',
          'secure notarization': 'secure notarization ',
          'anytime, anywhere': 'anytime, anywhere',
          'oboardingDescription2':
              'Elevate trust seamlessly notarize documents with notaryPing—instant, secure, and anywhere You need.',
          'Certified notaries': 'Certified notaries\n',
          'seal with confidence': 'seal with confidence\n',
          'on notaryping': 'on notaryping',
          'oboardingDescription3':
              'Unlock trust with certified notaries: seamless, secure notarization on Notaryping.confidence in every seal connect instantly, anytime, anywhere.',
          'Enter your email': 'Enter your email',
          'Enter your password': 'Enter your password',
          'Enter your email or number': 'Enter your email or number',
          "Let's Sign You In!": "Let's\nSign You In!",
          "Let's Sign You Up!": "Let's\nSign You Up!",
          'Sign Up!': 'Sign Up!',
          'Sign In': 'Sign In',
          'Forgot password': 'Forgot password?',
          'or': 'or',
          'Continue With Google': 'Continue With Google',
          'Continue With Facebook': 'Continue With Facebook',
          'Continue With Apple': 'Continue With Apple',
          'Already have an account?': 'Already have an account?',
          'Login': 'Login',
          'By signing in you accept our': 'By signing in you accept our ',
          'Terms of Services': 'Terms of Services ',
          'and': 'and ',
          'Privacy Policy.': 'Privacy Policy.',
          'Password is required': 'Password is required',
          '8characterslong': 'Password must be at least 8 characters long',
          'ConfirmPassword': 'Confirm Password must be same to Password',
          'emailaddress': 'Please enter a valid email address',
          'Email is required': 'Email is required',
          'Name is required': 'Name is required',
          'confirmPassword': 'Confirm password',
          'Enter your name': 'Enter your name',
          'Register': 'Register',
          'Create your account now': 'Create your account now',
          'Forgot password?': 'Forgot password?',
          'foegotDescription':
              'Don’t worry! it happens, Please enter the email address associated with your account.',
          'send': 'send',
          'Sign up': 'Sign up',
          'otpDescription':
              'We just sent you an email with 4-digit code. looks like very soon you will be logged in!',
          'Verify': 'Verify',
          'Reset password': 'Reset password',
          'resetDescription':
              'Your password must be different from previously used  password',
          'Enter new password': 'Enter new password',
          'Home': 'Home',
          'Bookings': 'Bookings',
          'Message': 'Message',
          'Profile': 'Profile',
          'Booking': 'Booking',
          'History': 'History',
          'Currents booking': 'Currents booking',
          'Tracking': 'Tracking',
          'Signature for property documents':
              'Signature for property documents',
          "Don't Have an account?": "Don't Have an account?",
          'Edit profile': 'Edit profile',
          'App setting': 'App setting',
          'Change password': 'Change password',
          'Customer support': 'Customer support',
          'Terms and conditions': 'Terms and conditions',
          'Legal Policy': 'Legal Policy',
          'Log Out': 'Log Out',
          'State': 'State',
          'Enter your address': 'Enter your address',
          'Zip code': 'Zip code',
          'Enter current password': 'Enter current password',
          'Change': 'Change',
          'Privacy policy': 'Privacy policy',
          'Chat with support': 'Chat with support',
          'Our 24x7 customer service': 'Our 24x7 customer service',
          'Report id': 'Report id',
          'Delete': 'Delete',
          'Phone number': 'Phone number',
          'Only Push Notification will be disable!':
              'Only Push Notification will be disable!',
          'Notification': 'Notification',
          'Update': 'Update ',
          'Cancel booking': 'Cancel booking',
          'Send message': 'Send message',
          'Send booking request': 'Send booking request',
          'Request confirmed': 'Request confirmed',
          'Booking time': 'Booking time',
          'Finished booking': 'Finished booking',
          'Available notaries': 'Available notaries',
          'Are you sure do you want to cancel this booking':
              'Are you sure do you want to cancel this booking',
          'See all': 'See all',
          'Book appointment': 'Book appointment',
          'About': 'About',
          'Report this Notary': 'Report this Notary',
          'Services': 'Services',
          'Reviews': 'Reviews',
          'Report this notary': 'Report this notary',
          'Report type': 'Report type',
          'Description': 'Description',
          'Submit report': 'Submit report',
          'Address Book': 'Address Book',
          'Clear all': 'Clear all',
          '': '',
        },
      };
}
