name: notary_ping
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  page_transition: ^2.0.9
  flutter_staggered_animations: ^1.1.1
  pinput: ^3.0.1
  avatar_glow: ^2.0.2
  expandable_page_view: ^1.0.17
  intl:
  delayed_display: ^2.0.0
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  dots_indicator: ^3.0.0
  flutter_slidable_panel: ^1.1.3
  audioplayers: ^5.2.1
  cached_network_image: ^3.3.0
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.5.0
  label_marker: ^1.0.1
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - assets/onboarding-vectors/
    - assets/icon/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-Black.ttf
  